[package]
name = "gamelibrary"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
diff-struct = "0.5.3"
macroquad = {git = "https://github.com/VoxanyNet/macroquad", rev = "659081936a0e32befc63169391b7cc5a85801470"}
nalgebra = {git = "https://github.com/VoxanyNet/nalgebra"}
rand = "0.8.5"
rapier2d = {git = "https://github.com/VoxanyNet/rapier", rev = "48279009056d7c22035b2789ccc41f2bf552ea8d", features = ["serde-serialize"]}
serde = { version = "1.0.203", features = ["derive"] }
uuid = { version = "1.8.0", features = ["v4"] }
