[package]
name = "gamelibrary"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcode = { version = "0.6.3", features = ["serde"] }
chrono = "0.4.38"
diff-struct = "0.5.3"
ewebsock = "0.6.0"
fxhash = "0.2.1"
lz4_flex = "0.11.3"
macroquad = {git = "https://github.com/VoxanyNet/macroquad", rev = "659081936a0e32befc63169391b7cc5a85801470"}
nalgebra = {git = "https://github.com/VoxanyNet/nalgebra", rev = "e418ac27d31977ed36ee95f56d7ca18a490e0b33"}
rand = "0.8.5"
rapier2d = {git = "https://github.com/VoxanyNet/rapier", rev = "2d5007249371e380f3fad7fed446e0e4a9843eb6", features = ["serde-serialize"]}
serde = { version = "1.0.203", features = ["derive"] }
tungstenite = "0.23.0"
uuid = { version = "1.8.0", features = ["v4"] }
