[package]
name = "gamelibrary"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
diff-struct = "0.5.3"
macroquad = "0.4.7"
nalgebra = "0.32.5"
rand = "0.8.5"
rapier2d = "0.18.0"
serde = { version = "1.0.203", features = ["derive"] }
uuid = { version = "1.8.0", features = ["v4"] }
